# Generated by Django 5.1 on 2024-11-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='has_accessibility_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='other_accessibility_need',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accessibility_needs',
            field=models.ManyToManyField(blank=True, to='account.accessibilityneed'),
        ),
    ]
