# Generated by Django 5.1 on 2024-11-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accessibilityneed_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='other_accessibility_need',
        ),
    ]
