# Generated by Django 5.1 on 2024-11-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_media_blogpost_tags_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='media',
        ),
    ]
